# Generated by Django 4.2.7 on 2023-11-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertiser',
            options={'verbose_name': 'Рекламодатель', 'verbose_name_plural': 'Рекламодатели'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Раздел газеты', 'verbose_name_plural': 'Разделы газеты'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'verbose_name': 'Читатель', 'verbose_name_plural': 'Читатели'},
        ),
    ]
