# Generated by Django 4.2.7 on 2023-12-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiser',
            name='ads_published',
        ),
        migrations.AddField(
            model_name='advertiser',
            name='published_ads',
            field=models.ManyToManyField(blank=True, related_name='ads_published', to='newspaper.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='advertisers',
            field=models.ManyToManyField(blank=True, related_name='ads_published', to='newspaper.advertiser'),
        ),
    ]
